<?php

/**
 * Send a payment request to paybox
 */
function paybox_pay($cents, $order_id, $payer_email, $destination = '', $devise = 'euro') {
  // We keep a trace of the amount,
  // so that it can be verified on status update request
  $amounts = variable_get('paybox_order_amounts', array());
  $amounts[$order_id] = $cents;
  variable_set('paybox_order_amounts', $amounts);
  $devise_code = _paybox_devise_code($devise);
  $query = "cents=$cents&order_id=$order_id&payer_email=$payer_email&destination=$destination&devise=$devise_code";
  $path = drupal_get_path('module', 'paybox') . '/paybox_page.php';
  return array(
      $path,
      $query,
  );
}

/**
 * Implements hook_menu().
 */
function paybox_menu() {
  $items['paybox_back_page'] = array(
      'page callback' => '_paybox_back_page',
      'access callback' => TRUE,
  );
  $items['admin/settings/paybox'] = array(
      'title' => 'Paybox settings',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('paybox_settings_form'),
      'access arguments' => array('access administration pages'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'paybox.admin.inc',
  );
  return $items;
}

/**
 * Set a message and go to the destination page
 */
function _paybox_back_page() {
  $destination = $_GET['destination'];
  $result = $_GET['result'];
  switch ($result) {
    case 'effectue' :
      drupal_set_message(variable_get('paybox_effectue_message', t('Payment completed. Thank you.')), 'status');
      break;
    case 'refuse' :
      drupal_set_message(variable_get('paybox_refuse_message', t('Payment refused. Sorry.')), 'error');
      break;
    case 'annule' :
      drupal_set_message(variable_get('paybox_annule_message', t('Payment canceled.')), 'warning');
      break;
  }
  drupal_goto($destination, 'result=' . $result);
}

/**
 * Return the devise code from a string
 */
function _paybox_devise_code($devise) {
  //TODO : others
  static $codes = array(
      'euro' => '978',
      'USD' => '840',
  );
  return $codes[$devise];
}

/**
 * Check sign on paybox back request
 */
function _paybox_verif_sign() {
  //TODO
  return TRUE;
}
