paybox.settings:
  type: config_object
  mapping:
    paybox_activate_real_payments:
      type: boolean
      label: 'Activate real payments'
    paybox_production_host:
      type: varchar
      label: 'Paybox production host'
    paybox_production_hash_key:
      type: varchar
      label: 'Hash key for hmac mode Production'
    paybox_sandbox_host:
      type: varchar
      label: 'Paybox sandbox host'
    paybox_sandbox_hash_key:
      type: varchar
      label: 'Hash key for hmac mode Sandbox'
    paybox_PBX_SITE:
      type: varchar
      label: 'Site number'
    paybox_PBX_RANK:
      type: varchar
      label: 'Rank number'
    paybox_PBX_IDENTIFIANT:
      type: varchar
      label: 'PAYBOX identifier'
    paybox_authorized_ips:
      type: varchar
      label: 'Authorized ips on callback urls, comma separated'
    paybox_effectue_message:
      type: varchar
      label: 'Message when payment succeeded'
    paybox_refuse_message:
      type: varchar
      label: 'Message when payment was refused'
    paybox_annule_message:
      type: varchar
      label: 'Message when payment was cancelled'
